export type ProjectPhoto = {
  src: string;
  alt: string;
  w: number;
  h: number;
  category: "kitchen" | "bathroom" | "living room";
  stage: "finished" | "in-progress";
};

// Keys and filenames are legacy labels from the first asset pass and do not
// describe the photo (e.g. `jobsite` is a finished kitchen, `bathVanityGold` is
// a living room). `alt` and `category` were re-verified against the pixels on
// 2026-09-27 — pick photos by those, not by key/filename.
export const photos = {
  heroDining: {
    src: "/images/hero-kitchen-dining.jpg",
    alt: "Finished L & E bathroom with a freestanding tub and pebble-tile walk-in shower behind glass, with a hillside view through the window",
    w: 2000,
    h: 1500,
    category: "bathroom",
    stage: "finished",
  },
  heroIsland: {
    src: "/images/hero-kitchen-island.jpg",
    alt: "Bathroom with a glass walk-in shower, white tile with a mosaic accent strip, and a white vanity with dark counter",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  jobsite: {
    src: "/images/jobsite-exterior.jpg",
    alt: "Finished kitchen with white upper cabinets, gray-green lowers, a waterfall island, and globe pendant lights",
    w: 1500,
    h: 2000,
    category: "kitchen",
    stage: "finished",
  },
  kitchenWhiteGold: {
    src: "/images/kitchen-white-gold.jpg",
    alt: "Powder room with a textured dark accent wall, rustic wood towel ladder, and hanging pendant light",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  kitchenShaker: {
    src: "/images/kitchen-shaker.jpg",
    alt: "Kitchen with a wood-slat island, dark cabinetry, blue tile backsplash, and stainless built-in refrigerator",
    w: 1599,
    h: 1387,
    category: "kitchen",
    stage: "finished",
  },
  kitchenIslandClose: {
    src: "/images/kitchen-island-close.jpg",
    alt: "Bathroom with a double wood vanity, rounded mirrors, and a checkerboard tile floor",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  kitchenIslandGold: {
    src: "/images/kitchen-island-gold.jpg",
    alt: "Glass walk-in shower with brass fixtures and a lit niche beside a smart toilet",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  kitchenIslandWide: {
    src: "/images/kitchen-island-wide.jpg",
    alt: "Frameless glass walk-in shower with large-format tile and a pebble floor",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  kitchenProtected: {
    src: "/images/kitchen-protected.jpg",
    alt: "Bathroom with green vertical tile, a freestanding tub, glass shower, and bubble chandelier",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  kitchenInProgress: {
    src: "/images/kitchen-in-progress.jpg",
    alt: "Large tiled walk-in shower with a glass enclosure, corner bench, and recessed niche",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  kitchenFraming: {
    src: "/images/kitchen-framing.jpg",
    alt: "Bathroom with a grid-frame glass shower, gray subway tile, and patterned black-and-white floor tile",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  bathMarbleRain: {
    src: "/images/bath-marble-rain.jpg",
    alt: "Powder room with a sage-green vanity, arched brass mirror, and warm accent lighting",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  bathVanityGold: {
    src: "/images/bath-vanity-gold.jpg",
    alt: "Finished living room with a stacked-stone fireplace wall, arched window, and large-format tile floor",
    w: 1500,
    h: 2000,
    category: "living room",
    stage: "finished",
  },
  bathHexShower: {
    src: "/images/bath-hex-shower.jpg",
    alt: "Galley kitchen with dark cabinetry, marble-look counters, undermount sink, and gas range",
    w: 1600,
    h: 1200,
    category: "kitchen",
    stage: "finished",
  },
  bathGlassShower: {
    src: "/images/bath-glass-shower.jpg",
    alt: "Walk-in shower with a glass panel, pebble floor, built-in bench, and lit niche",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  bathShowerToilet: {
    src: "/images/bath-shower-toilet.jpg",
    alt: "Primary bathroom with a freestanding tub, marble-look glass shower, and ceiling fan",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  bathProgressGold: {
    src: "/images/bath-progress-gold.jpg",
    alt: "Bathroom with a glass shower, wave-texture tile, black vanity, and backlit mirror",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  bathProgressRoom: {
    src: "/images/bath-progress-room.jpg",
    alt: "Walk-in shower with a mirrored mosaic accent wall, pebble floor, and grab bar",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  bathNiche: {
    src: "/images/bath-niche.jpg",
    alt: "Half bath with hexagon floor tile, a white vanity, and an octagonal mirror",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  bathVanityBoxes: {
    src: "/images/bath-vanity-boxes.jpg",
    alt: "Bathroom vanity with a lighted mirror, brass sconces, and botanical wallpaper",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  bathMarbleProcess: {
    src: "/images/bath-marble-process.jpg",
    alt: "Gray-tile walk-in shower with a glass door, bench, and wall-hung toilet",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  bathMarbleClose: {
    src: "/images/bath-marble-close.jpg",
    alt: "Bathroom with a freestanding tub inside a glass shower enclosure, pebble floor, and checkerboard tile",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  bathMarbleDetail: {
    src: "/images/bath-marble-detail.jpg",
    alt: "Vessel sink on a live-edge wood vanity with a wall-mounted black faucet",
    w: 1500,
    h: 1999,
    category: "bathroom",
    stage: "finished",
  },
  bathMarbleWide: {
    src: "/images/bath-marble-wide.jpg",
    alt: "Bathroom with a double vanity, brass fixtures, and two curved mirrors",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  bathMarbleCorner: {
    src: "/images/bath-marble-corner.jpg",
    alt: "Vanity with gray cabinets and a white counter beside a stacked-stone accent wall and window",
    w: 1500,
    h: 1999,
    category: "bathroom",
    stage: "finished",
  },
} as const satisfies Record<string, ProjectPhoto>;

export const gallery: ProjectPhoto[] = [
  photos.kitchenWhiteGold,
  photos.bathMarbleRain,
  photos.heroDining,
  photos.bathVanityGold,
  photos.kitchenIslandClose,
  photos.bathHexShower,
  photos.heroIsland,
  photos.bathGlassShower,
  photos.kitchenIslandGold,
  photos.bathShowerToilet,
  photos.kitchenShaker,
  photos.kitchenIslandWide,
  photos.jobsite,
  photos.kitchenInProgress,
  photos.bathProgressGold,
  photos.kitchenFraming,
  photos.bathNiche,
  photos.bathProgressRoom,
];

export const kitchenGallery = gallery.filter((p) => p.category === "kitchen");
export const bathroomGallery = gallery.filter((p) => p.category === "bathroom");
