export type ProjectPhoto = {
  src: string;
  alt: string;
  w: number;
  h: number;
  category: "kitchen" | "bathroom" | "jobsite";
  stage: "finished" | "in-progress";
};

export const photos = {
  heroDining: {
    src: "/images/hero-kitchen-dining.jpg",
    alt: "Finished kitchen and dining room with marble island, white cabinetry, and chandelier—L & E Construction Group project",
    w: 2000,
    h: 1500,
    category: "kitchen",
    stage: "finished",
  },
  heroIsland: {
    src: "/images/hero-kitchen-island.jpg",
    alt: "Kitchen with dark island, marble counters, white cabinetry, and pendant lighting",
    w: 2000,
    h: 1500,
    category: "kitchen",
    stage: "finished",
  },
  jobsite: {
    src: "/images/jobsite-exterior.jpg",
    alt: "Active L & E Construction Group jobsite at a Santa Ana-area home, with materials staged at the curb",
    w: 2000,
    h: 1500,
    category: "jobsite",
    stage: "in-progress",
  },
  kitchenWhiteGold: {
    src: "/images/kitchen-white-gold.jpg",
    alt: "White shaker kitchen with gold hardware, marble island, and farmhouse sink",
    w: 1500,
    h: 2000,
    category: "kitchen",
    stage: "finished",
  },
  kitchenShaker: {
    src: "/images/kitchen-shaker.jpg",
    alt: "White shaker kitchen with dark counters and a farmhouse sink",
    w: 1599,
    h: 1387,
    category: "kitchen",
    stage: "finished",
  },
  kitchenIslandClose: {
    src: "/images/kitchen-island-close.jpg",
    alt: "Close view of a marble kitchen island with gold faucet and cabinetry",
    w: 1500,
    h: 2000,
    category: "kitchen",
    stage: "finished",
  },
  kitchenIslandGold: {
    src: "/images/kitchen-island-gold.jpg",
    alt: "Kitchen island with marble top, gold faucet, and white cabinetry",
    w: 1500,
    h: 2000,
    category: "kitchen",
    stage: "finished",
  },
  kitchenIslandWide: {
    src: "/images/kitchen-island-wide.jpg",
    alt: "Wide view of a finished kitchen island and surrounding cabinetry",
    w: 1500,
    h: 2000,
    category: "kitchen",
    stage: "finished",
  },
  kitchenProtected: {
    src: "/images/kitchen-protected.jpg",
    alt: "Kitchen remodel in progress with floors protected during finishing",
    w: 1500,
    h: 2000,
    category: "kitchen",
    stage: "in-progress",
  },
  kitchenInProgress: {
    src: "/images/kitchen-in-progress.jpg",
    alt: "Kitchen remodel in progress with cabinets set and surfaces protected",
    w: 2000,
    h: 1500,
    category: "kitchen",
    stage: "in-progress",
  },
  kitchenFraming: {
    src: "/images/kitchen-framing.jpg",
    alt: "Kitchen remodel during framing, drywall, and cabinet installation",
    w: 2000,
    h: 1500,
    category: "kitchen",
    stage: "in-progress",
  },
  bathMarbleRain: {
    src: "/images/bath-marble-rain.jpg",
    alt: "Walk-in marble shower with gold rain head and glass enclosure",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  bathVanityGold: {
    src: "/images/bath-vanity-gold.jpg",
    alt: "Bathroom vanity with marble counter, gold faucet, and wallpaper",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  bathHexShower: {
    src: "/images/bath-hex-shower.jpg",
    alt: "Bathroom with white subway tile, black hexagon floor, and glass shower",
    w: 1600,
    h: 1200,
    category: "bathroom",
    stage: "finished",
  },
  bathGlassShower: {
    src: "/images/bath-glass-shower.jpg",
    alt: "Walk-in shower with marble-look tile and glass door",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  bathShowerToilet: {
    src: "/images/bath-shower-toilet.jpg",
    alt: "Bathroom interior with walk-in shower, toilet, and marble tile",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "finished",
  },
  bathProgressGold: {
    src: "/images/bath-progress-gold.jpg",
    alt: "Bathroom shower tile and gold fixtures during remodel",
    w: 2000,
    h: 1500,
    category: "bathroom",
    stage: "in-progress",
  },
  bathProgressRoom: {
    src: "/images/bath-progress-room.jpg",
    alt: "Bathroom remodel in progress showing shower, vanity, and toilet",
    w: 2000,
    h: 1500,
    category: "bathroom",
    stage: "in-progress",
  },
  bathNiche: {
    src: "/images/bath-niche.jpg",
    alt: "Shower niche and gold fixtures during a bathroom remodel",
    w: 2000,
    h: 1500,
    category: "bathroom",
    stage: "in-progress",
  },
  bathVanityBoxes: {
    src: "/images/bath-vanity-boxes.jpg",
    alt: "Bathroom vanity and shower during finishing",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "in-progress",
  },
  bathMarbleProcess: {
    src: "/images/bath-marble-process.jpg",
    alt: "Marble shower during construction",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "in-progress",
  },
  bathMarbleClose: {
    src: "/images/bath-marble-close.jpg",
    alt: "Marble shower interior during construction",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "in-progress",
  },
  bathMarbleDetail: {
    src: "/images/bath-marble-detail.jpg",
    alt: "Detail of marble shower walls during a remodel",
    w: 1500,
    h: 1999,
    category: "bathroom",
    stage: "in-progress",
  },
  bathMarbleWide: {
    src: "/images/bath-marble-wide.jpg",
    alt: "Wide view of a marble shower during construction",
    w: 1500,
    h: 2000,
    category: "bathroom",
    stage: "in-progress",
  },
  bathMarbleCorner: {
    src: "/images/bath-marble-corner.jpg",
    alt: "Corner detail of a marble shower remodel",
    w: 1500,
    h: 1999,
    category: "bathroom",
    stage: "in-progress",
  },
} as const satisfies Record<string, ProjectPhoto>;

export const gallery: ProjectPhoto[] = [
  photos.kitchenWhiteGold,
  photos.bathMarbleRain,
  photos.heroDining,
  photos.bathVanityGold,
  photos.kitchenIslandClose,
  photos.bathHexShower,
  photos.heroIsland,
  photos.bathGlassShower,
  photos.kitchenIslandGold,
  photos.bathShowerToilet,
  photos.kitchenShaker,
  photos.kitchenIslandWide,
  photos.jobsite,
  photos.kitchenInProgress,
  photos.bathProgressGold,
  photos.kitchenFraming,
  photos.bathNiche,
  photos.bathProgressRoom,
];

export const kitchenGallery = gallery.filter((p) => p.category === "kitchen");
export const bathroomGallery = gallery.filter((p) => p.category === "bathroom");
